/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Divider: typeof import('./src/components/Divider.vue')['default']
    Education: typeof import('./src/components/Education.vue')['default']
    Hello: typeof import('./src/components/Hello.vue')['default']
    Profile: typeof import('./src/components/Profile.vue')['default']
    SideProject: typeof import('./src/components/SideProject.vue')['default']
    Skills: typeof import('./src/components/Skills.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    WorkExperience: typeof import('./src/components/WorkExperience.vue')['default']
  }
}
